# Generated by Django 4.1.1 on 2022-10-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_collage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='img_str',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
