# Generated by Django 4.1.1 on 2022-10-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_collage', '0002_display_collage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='id',
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
