# Generated by Django 4.1.1 on 2022-10-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_collage', '0006_alter_album_cover_art_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_art_img',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
