# Generated by Django 4.1.1 on 2022-10-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_collage', '0008_collage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='img',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
