# Generated by Django 4.1.1 on 2022-10-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_collage', '0009_alter_collage_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='name',
            field=models.TextField(default='filler'),
        ),
    ]
