# Generated by Django 4.1.1 on 2022-10-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_collage', '0010_collage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collage',
            name='name',
        ),
    ]
